[package]
name = "reqr"
version = "0.1.0"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]
description = "Perform http requests"

[dependencies]
hyper = "0.12"
hyper-tls = "0.2"
clap = "2.31.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.7"
syntect = "2.1"
